title: taylanbil.github.io
description: Math, Data, Python, Machine Learning @ Facebook
show_downloads: false
google_analytics: UA-106417291-1
theme: jekyll-theme-hacker
exclude: ["makepost.sh", "README.md", "nbs"]
